### ISSUE TITLE
Why was "Calc" Disabled?

### ISSUE THREAD

**Issue by TerrinX** [LEv145/--sd-webui-ar-plus#1]
Calc was arguably the most important feature for me personally, so I could scale up images while retaining their aspect ratio without doing the math myself. I am baffled why it was disabled at all

**Comment by LEv145** [comment]
Thanks, I'll try to add "enable Calc" in the settings

**Comment by LEv145** [comment]
I studied `Calc` feature and returned it, a handy thing
