### ISSUE TITLE
The "Switch" button errors when clicked [FORGE]

### ISSUE THREAD

**Issue by LEv145** [LEv145/--sd-webui-ar-plus#26]
# Error
```
  File "C:\Users\OFFICE\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\OFFICE\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\OFFICE\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\OFFICE\AppData\Local\Programs\Python\Python310\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)

The above 4 lines repeat many times before...

TypeError: cannot pickle '_thread.lock' object
```

# Possible solution
https://www.gradio.app/docs/gradio/state

**Comment by LEv145** [comment]
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/300

**Comment by altoiddealer** [comment]
It could have something to do with the global variable.

Take a look at how I mitigated the global variables [here](https://github.com/altoiddealer/--sd-webui-ar-plusplus/blob/main/scripts/sd-webui-ar-plusplus.py#L15) and [here](https://github.com/altoiddealer/--sd-webui-ar-plusplus/blob/main/scripts/sd-webui-ar-plusplus.py#L336)

**Comment by LEv145** [comment]
https://github.com/LEv145/--sd-webui-ar-plus/tree/fix-forge-arc-logic-buttons

**Comment by altoiddealer** [comment]
I tested this in Forge - the button logic is now working without any errors.

There is a problem though - once clicked, the icon vanishes and does not ever restore.

Unclicked:

![Screenshot 2024-08-21 141458](https://github.com/user-attachments/assets/9a6fd612-c353-4584-926b-6fe1b04cc31d)

Clicked once:

![Screenshot 2024-08-21 141545](https://github.com/user-attachments/assets/bcd8f3a0-8fc3-4fac-9eaa-d872d72b0741)

Clicked again:

![Screenshot 2024-08-21 141434](https://github.com/user-attachments/assets/91595141-7bdd-4409-a355-adb00b3be1e0)

**Comment by LEv145** [comment]
I understand, I'll have to recreate the buttons

**Comment by LEv145** [comment]
https://github.com/LEv145/--sd-webui-ar-plus/commit/27ef14b08751c0bb4c77c06c09cb275745e9d565
https://github.com/LEv145/--sd-webui-ar-plus/commit/310a2df9d72fbdbf1a1252e592fe8d3883101eac

**Comment by altoiddealer** [comment]
> [27ef14b](https://github.com/LEv145/--sd-webui-ar-plus/commit/27ef14b08751c0bb4c77c06c09cb275745e9d565) [310a2df](https://github.com/LEv145/--sd-webui-ar-plus/commit/310a2df9d72fbdbf1a1252e592fe8d3883101eac)

This makes the whole button disappear when clicked XD

![Screenshot 2024-08-21 142846](https://github.com/user-attachments/assets/937453d7-cad8-4f40-836d-54883aa13302)

In my version, I actually change the button value (icon string) when clicked (not the gradio variant attribute for primary/secondary), which is why I change the "value" of the button when clicked (which is the Icon string).

I think you were close originally but the function was trying to update the value, not just the variant?

**Comment by LEv145** [comment]
Oops, I think I made a little mistake in the line :D
https://github.com/LEv145/--sd-webui-ar-plus/commit/3199e772b27be1950eb4c2e9297c3a0823478763
https://github.com/LEv145/--sd-webui-ar-plus/commit/00b7978f8425135427f200476e98590127ce7758



The problem here is that the `.update()` method is deprecated and broken in Gradio 4, so I'm recreating object as the developer advises:
https://github.com/gradio-app/gradio/issues/6339
> Removes the deprecated `.update()` method from component classes. Instead, you can now just return an instance of a component from your function. I.e. return `gr.Textbox(lines=4)` instead of `gr.Textbox.update(lines=4)`

But `gr.update` seems to still work
https://github.com/altoiddealer/--sd-webui-ar-plusplus/blob/8b900cd2748f95bce455db62ba0cb08093a3ca59/scripts/sd-webui-ar-plusplus.py#L439

**Comment by LEv145** [comment]
https://github.com/gradio-app/gradio/issues/5863

**Comment by altoiddealer** [comment]
The SD WebUI guys don't just import gradio and call it a day - they have all sorts of patches and stuff that I can't comprehend, which probably convert a lot of bad code into good code.  It's very likely that there's something in there fixing the `gr.update`

I can't claim to understand that code well, I definitely relied hard on your code / ChatGPT.


The new commit is working in Forge... but unfortunately, that button is erroring in A1111

```
  File "D:\0_AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\encoders.py", line 148, in jsonable_encoder
    if isinstance(obj, classes_tuple):
  File "C:\Users\RandallSu\AppData\Local\Programs\Python\Python310\lib\abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by LEv145** [comment]
Okay, then it makes sense to use `gr.update`

**Comment by LEv145** [comment]
In theory it should work

https://github.com/LEv145/--sd-webui-ar-plus/commit/670146696391617f922559addb64f30167d79a5b

**Comment by LEv145** [comment]
I think in `Gradio 4` they left the option to use `gr.update`

But, unfortunately, they did not write how to simply switch from `Gradio 3` to `Gradio 4`

**Comment by altoiddealer** [comment]
Good news!  It's now working in A111 and Forge :)

Thanks again for coming up with the solution to our main problem, it was driving me insane!
